### PR TITLE
11.0 add account invoice import facturae

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
@etobella Can you rebase your branch to OCA/11.0? I am adding some improvements to this PR in 
c6ea3c0

I was able to import a facturae from Endesa, but had to:
1) Change the schema to 3.2.1
2) Add the Utilities extension xsd (I also added other available extensions)

### CODE REVIEW

**Comment by etobella** [comment]
I rebased, but I think it is not a good solution to make the change directly. I think it would be better to check both systems in order to be sure that all works perfectly (both versions are currently accepted)

**Comment by JordiBForgeFlow** [comment]
Right... I will try to load all the versions into a single facturae wrapper. After all each schema has it's own namespace. So the XML validation should consider validating against the right namespace.

**Comment by etobella** [comment]
Don't worry. I cherry-picker your commit and I am currently working on it :wink:

**Comment by etobella** [comment]
Changes applied.

**Pull request closed without merging**
